name: deepLearn_CPU
channels:
- !!python/unicode
  'defaults'
dependencies:
- python=3.6.5
- pip=10.0.1
- numpy=1.14.3
- jupyter=1.0.0
- matplotlib=2.2.2
- scikit-learn=0.19.1
- scipy=1.1.0
- pandas=0.23.0
- pillow=5.1.0
- seaborn=0.8.1
- h5py=2.8.0
- pip:
  - tensorflow==1.6.0
  - keras==2.1.5
