name: deepLearn_V4
channels:
  - defaults
dependencies:
  - ipykernel=5.1.4
  - python=3.7.6
  - matplotlib=3.1.3
  - numpy=1.19.5
  - pandas=1.0.1
  - seaborn=0.10.0
  - scipy=1.4.1
  - sqlite=3.31.1
  - numba=0.48.0
  - scikit-learn=0.22.1
  - h5py=2.10.0
  - pip
  - pip:
      - keras==2.3.1
      - tensorboard
      - tensorflow-gpu==2.0.0
